/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GenerateImageArgs = IDL.Record({
  'model' : IDL.Text,
  'positivePrompt' : IDL.Text,
  'temperature' : IDL.Float64,
  'seed' : IDL.Int,
  'negativePrompt' : IDL.Text,
  'aspectRatio' : IDL.Text,
});
export const GenerateImageResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const PoseCriteria = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Float64,
  'height' : IDL.Float64,
  'cameraAngle' : IDL.Text,
  'clothing' : IDL.Text,
  'situationFiguration' : IDL.Text,
  'situationPose' : IDL.Text,
  'lighting' : IDL.Text,
  'artStyle' : IDL.Text,
  'environment' : IDL.Text,
  'cameraLens' : IDL.Text,
  'ethnicity' : IDL.Text,
  'situationPosing' : IDL.Text,
  'negativePrompt' : IDL.Text,
  'bodyType' : IDL.Text,
  'composition' : IDL.Text,
  'situationBehavior' : IDL.Text,
  'aspectRatio' : IDL.Text,
});
export const Preset = IDL.Record({
  'name' : IDL.Text,
  'criteria' : PoseCriteria,
});
export const Time = IDL.Int;
export const PromptHistory = IDL.Record({
  'timestamp' : Time,
  'criteria' : PoseCriteria,
  'prompt' : IDL.Text,
});
export const Header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(Header),
  }),
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(Header),
});

export const idlService = IDL.Service({
  'generateImage' : IDL.Func(
      [GenerateImageArgs, IDL.Text, IDL.Text],
      [GenerateImageResult],
      [],
    ),
  'getPresets' : IDL.Func([], [IDL.Vec(Preset)], ['query']),
  'getPromptHistory' : IDL.Func([], [IDL.Vec(PromptHistory)], ['query']),
  'getSituationBehaviors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'legacyGenerateImage' : IDL.Func(
      [GenerateImageArgs],
      [GenerateImageResult],
      [],
    ),
  'savePreset' : IDL.Func([IDL.Text, PoseCriteria], [IDL.Bool], []),
  'sendQueries' : IDL.Func([PoseCriteria, IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GenerateImageArgs = IDL.Record({
    'model' : IDL.Text,
    'positivePrompt' : IDL.Text,
    'temperature' : IDL.Float64,
    'seed' : IDL.Int,
    'negativePrompt' : IDL.Text,
    'aspectRatio' : IDL.Text,
  });
  const GenerateImageResult = IDL.Variant({
    'ok' : IDL.Text,
    'err' : IDL.Text,
  });
  const PoseCriteria = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Float64,
    'height' : IDL.Float64,
    'cameraAngle' : IDL.Text,
    'clothing' : IDL.Text,
    'situationFiguration' : IDL.Text,
    'situationPose' : IDL.Text,
    'lighting' : IDL.Text,
    'artStyle' : IDL.Text,
    'environment' : IDL.Text,
    'cameraLens' : IDL.Text,
    'ethnicity' : IDL.Text,
    'situationPosing' : IDL.Text,
    'negativePrompt' : IDL.Text,
    'bodyType' : IDL.Text,
    'composition' : IDL.Text,
    'situationBehavior' : IDL.Text,
    'aspectRatio' : IDL.Text,
  });
  const Preset = IDL.Record({ 'name' : IDL.Text, 'criteria' : PoseCriteria });
  const Time = IDL.Int;
  const PromptHistory = IDL.Record({
    'timestamp' : Time,
    'criteria' : PoseCriteria,
    'prompt' : IDL.Text,
  });
  const Header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : IDL.Record({
      'status' : IDL.Nat,
      'body' : IDL.Vec(IDL.Nat8),
      'headers' : IDL.Vec(Header),
    }),
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(Header),
  });
  
  return IDL.Service({
    'generateImage' : IDL.Func(
        [GenerateImageArgs, IDL.Text, IDL.Text],
        [GenerateImageResult],
        [],
      ),
    'getPresets' : IDL.Func([], [IDL.Vec(Preset)], ['query']),
    'getPromptHistory' : IDL.Func([], [IDL.Vec(PromptHistory)], ['query']),
    'getSituationBehaviors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'legacyGenerateImage' : IDL.Func(
        [GenerateImageArgs],
        [GenerateImageResult],
        [],
      ),
    'savePreset' : IDL.Func([IDL.Text, PoseCriteria], [IDL.Bool], []),
    'sendQueries' : IDL.Func([PoseCriteria, IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };