/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GenerateImageArgs {
  'model' : string,
  'positivePrompt' : string,
  'temperature' : number,
  'seed' : bigint,
  'negativePrompt' : string,
  'aspectRatio' : string,
}
export type GenerateImageResult = { 'ok' : string } |
  { 'err' : string };
export interface Header { 'value' : string, 'name' : string }
export interface PoseCriteria {
  'age' : bigint,
  'weight' : number,
  'height' : number,
  'cameraAngle' : string,
  'clothing' : string,
  'situationFiguration' : string,
  'situationPose' : string,
  'lighting' : string,
  'artStyle' : string,
  'environment' : string,
  'cameraLens' : string,
  'ethnicity' : string,
  'situationPosing' : string,
  'negativePrompt' : string,
  'bodyType' : string,
  'composition' : string,
  'situationBehavior' : string,
  'aspectRatio' : string,
}
export interface Preset { 'name' : string, 'criteria' : PoseCriteria }
export interface PromptHistory {
  'timestamp' : Time,
  'criteria' : PoseCriteria,
  'prompt' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : {
    'status' : bigint,
    'body' : Uint8Array,
    'headers' : Array<Header>,
  },
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<Header>,
}
export interface _SERVICE {
  'generateImage' : ActorMethod<
    [GenerateImageArgs, string, string],
    GenerateImageResult
  >,
  'getPresets' : ActorMethod<[], Array<Preset>>,
  'getPromptHistory' : ActorMethod<[], Array<PromptHistory>>,
  'getSituationBehaviors' : ActorMethod<[], Array<string>>,
  'legacyGenerateImage' : ActorMethod<[GenerateImageArgs], GenerateImageResult>,
  'savePreset' : ActorMethod<[string, PoseCriteria], boolean>,
  'sendQueries' : ActorMethod<[PoseCriteria, string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];